[package]
name = "essential-scripts-rs"
version = "0.1.0"
edition = "2024"
description = "A set of useful tools for data wrangling"
publish = false

[dependencies]
clap = { version = "4.5", features = ["derive"] }

[dependencies.polars]
version = "0.52"
features = ["lazy", "strings", "concat_str", "timezones"]

[profile.release]
opt-level = 3
strip = "debuginfo"
lto = true

[profile.release.build-override]
opt-level = 3
codegen-units = 1

[dev-dependencies]
polars-testing = "0.52.0"
