permissions:
  contents: write
  pull-requests: write

name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v5
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.GH_TOKEN }}
          release-type: rust
      - name: Tag Latest Release as Stable
        if: ${{ steps.release-please.outputs.release_created }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add gh-token "https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git"
          git tag -d stable || true
          git push origin :stable || true
          git tag -a stable -m "Tag latest release as stable"
          git push origin stable
      - uses: actions/checkout@v6
        if: ${{ steps.release-please.outputs.release_created }}
      - name: Build Minimal
        if: ${{ steps.release-please.outputs.release_created }}
        run: cargo build --no-default-features
      - name: Build Docs
        if: ${{ steps.release-please.outputs.release_created }}
        run: cargo run --no-default-features -- --markdown-help